version: "3.9"
services: 
  redditbot:
    image: nlanson/shepard
    container_name: "ShepardBot"
    volumes:
      - "./shepard/.env:/app/.env" # Copy local env file into build directory for use.
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: nlanson/husky
    container_name: "PastaBackend"
    volumes:
      - "./husky/pastas.db:/app/pastas.db" # Copy local Sqlite file into running directory for use.
      - "./husky/.env:/app/.env"
    ports:
      - "8000:8000"
      # change to 8083:8000 for server production