name: Docker CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
          
      - name: Build db
        run: |
          docker build -t nlanson/husky ./husky --no-cache
      - name: Build bot
        run: |
          docker build -t nlanson/shepard ./shepard --no-cache
      
      - name: Push db
        run: |
          docker push nlanson/husky
      - name: Push bot
        run: |
          docker push nlanson/shepard
